### PR TITLE
Bootstrap

### PR DESCRIPTION
**Pull request by armanbilge**
- fixup the build
- cross-build for Native
- add a simple test

### CODE REVIEW

**Comment by armanbilge** [comment]
Ruh-roh?
```
failing seed for GeneratorsCheck.generates xml is 2vlpy64yIOKuEnqKnWrPi2mnlyiIXmu-8aZUOMf2qcL=
[info] ! GeneratorsCheck.generates xml: Exception raised on property evaluation.
[info] > Exception: java.lang.IllegalArgumentException: ʾ館뭆焲뭓鄹 must be an XML Name
[info] Failed: Total 1, Failed 0, Errors 1, Passed 0
[error] Error during tests:
[error] 	org.typelevel.scalacheck.xml.GeneratorsCheck
[error] (coreNative / Test / test) sbt.TestsFailedException: Tests unsuccessful
```

**Comment by rossabaker** [comment]
So, I can't build this locally:

```
sbt:root> coreNative/test
[error] Problem running '/usr/bin/clang --version'. Please check clang setup.
[error] Refer to (http://www.scala-native.org/en/latest/user/setup.html)
[error] (Global / nativeConfig) Problem running '/usr/bin/clang --version'. Please check clang setup.
[error] Refer to (http://www.scala-native.org/en/latest/user/setup.html)
[error] Total time: 1 s, completed Jun 16, 2022, 4:46:58 PM
```

I need at least three unique JVMs and develop on multiple machines, and that's the "easy" platform.  I'm a stickler for development shells.  I see the Scala Native instructions have a Nix environment.  If that were integrated with typelevel-nix, it'd be fine for me and an increasing number of others, but most new contributors don't use it.  (This project won't ever have many contributors, but I don't imagine PRs like this stop here...)

I also don't know anything about Scala Native.  If this unblocks something important, I'm willing to give it a try, but I'll be even more helpless than on Scala.js when it acts up.  This is likely to become burdensome for you unless there's a critical mass of maintainers with similar interests.

On a less fretful note, having a test is great.

**Comment by armanbilge** [comment]
/shrug Native for this project isn't important yet, it was just low-hanging fruit. Feel free to remove it.

It sounds to me there is a bigger discussion here for Scala Native and I don't have good answers for you. Scalacheck and Cats already had it, scodec, cats-parse and friends are getting it, and there's interest in it in Cats Effect and up. Contributors seem to manage okay in Cats, but maybe the ones for whom this is a blocker are staying silent.

**Comment by rossabaker** [comment]
I haven't built any of those projects locally in months, so this is all new to me.  I also thought it was tabled on Cats-Effect long ago, so that revival is also news to me.

I was able to integrate scala-native's Nix script and get a working dev shell on my current machine: https://github.com/typelevel/typelevel-nix/pull/46.  That fixes my problem.  Others can speak up for themselves.  My error came with a nice link, at least.

I'm also concerned about how many people know how to maintain the platform, but nobody is going to use it until there are libraries, and there won't be libraries until people use it, so someone has to bootstrap it.  I'm glad you're not as old and tired as me!

**Pull request merged**
